---
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - delegated


Docker Oracle DB 12:
  stage: deployment test
  script:
    - molecule test -s docker-oracle-12
  tags:
    - docker

Docker Oracle DB 11:
  stage: deployment test
  script:
    - molecule test -s docker-oracle-11
  tags:
    - docker

Docker Oracle DB XE:
  stage: deployment test
  script:
    - molecule test -s docker-oracle-xe
  tags:
    - docker


AWS Oracle DB 12:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-oracle-12-delegated
  tags:
    - delegated

AWS Oracle DB 11:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-oracle-11-delegated
  tags:
    - delegated

AWS Oracle DB XE:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-oracle-xe-delegated
  tags:
    - delegated


EPC Oracle DB 11:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-oracle-11-delegated
  tags:
    - delegated

EPC Oracle DB 12:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-oracle-12-delegated
  tags:
    - delegated

EPC Oracle DB XE:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-oracle-xe-delegated
  tags:
    - delegated
