---
- name: Install oracle-db
  hosts: oracle_db_ct
  pre_tasks:
    - name: "Adding hostname entry in /etc/hosts"
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ ansible_default_ipv4.address }}"
        line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}"
        unsafe_writes: True
      become: True
  vars:
    oracle_version: 11
    patch_version: 11.2.0.4
    transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-install/11g/11.2.0.4"
    oracle_images:
      - p13390677_112040_Linux-x86-64_1of7.zip
      - p13390677_112040_Linux-x86-64_2of7.zip
    oracle_db_swapfile: "/oracle-swapfile-docker-11"
    oracle_db_swap_count: 2096
    db_port: 1522
  roles:
    - role: ansible-role-oracle-db
  become: True
