---
- name: Install oracle-db
  hosts: oracle_db_ct
  vars:
    oracle_version: xe
    transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-install"
    oracle_images:
      - linux.x64_11gR2_xe.zip
    oracle_db_swapfile: "/oracle-swapfile-docker-xe"
    oracle_db_swap_count: 3072
  roles:
    - role: ansible-role-oracle-db
  become: True
